apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user-service-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata: 
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: bayrambayraktar/node-product-user-service
          ports:
            - containerPort: 3000 