apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    app: user-service #pod alanındaki metadata>labels>app:.. kısımı ile ayını olursa eşleşme sağlanır
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000